"""Shared building blocks for the uallak "agent house blueprint".

Every agent (hand-written or generated by architect_agent) uses these so that
logging, timing, and alerting look identical everywhere. The full blueprint —
rules and a copyable starting point — lives in agents/_template_agent.py and
.claude/skills/new-agent/SKILL.md.
"""
import time
from datetime import datetime

from agents.master_agent import alert as _master_alert


def log_step(agent_name: str, step: str, message: str = ""):
    """Standard log line: [ISO timestamp] [AGENT_NAME] step — message."""
    suffix = f" — {message}" if message else ""
    print(f"[{datetime.now().isoformat()}] [{agent_name.upper()}] {step}{suffix}")


def timed_step(agent_name: str, step: str, fn):
    """Run fn() and log start/finish with duration in the standard format."""
    t0 = time.perf_counter()
    log_step(agent_name, step, "starting")
    result = fn()
    log_step(agent_name, step, f"finished (took {time.perf_counter() - t0:.1f}s)")
    return result


def agent_alert(agent_name: str, issues: list):
    """Flag a failure that needs human attention. Logs in the standard alert
    format and appends it to the alert history that monitor_agent's deep scan
    reads on its next pass."""
    _master_alert(agent_name, issues)
